name: CMake

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install gcc-12
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends gcc-12 g++-12 gcovr
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-12 12
          sudo update-alternatives --config gcc
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test Coverage
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target coverage || exit 0
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ${{github.workspace}}/build/coverage
      - name: Test
        working-directory: ${{github.workspace}}/build/base64-test
        run: ctest -C ${{env.BUILD_TYPE}}
